#!/bin/sh

# TODO NOW DEBUG
# "pakt di foo bar +baz : 'quz' " only registers foo

set -eu

# Prints a given message in red and exits with status code 1.
fail() {
	printf "\x1b[31m$1\x1b[39m\n"
	exit 1
}

# Setting default options for config variables
: "${PAKT_CONF_PATH:=${XDG_CONFIG_HOME:-$HOME/.config}}"
. "$PAKT_CONF_PATH/pakt.conf"

: "${PAKT_CAT_PATH:=${XDG_DATA_HOME:-$HOME/.local/share}/pakt}"
: "${PAKT_EDITOR:=${EDITOR:-nano}}"
: "${CAT_SYNTAX:="+"}"
: "${NO_ARG_ACTION:="pakt help"}"
[ "$NO_ARG_ACTION" = "pakt" ] && {
	fail "You can't set NO_ARG_ACTION to 'pakt' at $PAKT_CONF_PATH/pakt.conf!
It causes a stack overflow."
}
: "${DEFAULT_CATS:=""}"
: "${REMOVE_EMPTY_CATS:=0}"
mkdir -p "$PAKT_CAT_PATH"

if [ $# -eq 0 ]; then
	$NO_ARG_ACTION
	exit
fi

# Just prints a help message.
help() {
	echo "pakt – a package manager wrapper with support for categorizing

Usage:
    pakt                                          perform a user-defined arbitrary action
    pakt i(nstall)          (pkg [+cat ...])...   install packages
    pakt u(ninstall)        (pkg [+cat ...])...   uninstall packages
    pakt d(ry-)i(nstall)    (pkg [+cat ...])...   write packages into categories without
                                                    installing them
    pakt d(ry-)u(ninstall)  (pkg [+cat ...])...   remove packages from categories without
                                                    uninstalling them
    pakt s(ync-)i(nstall)   (file | +cat)...      install several packages from categories
                                                    or arbitrary files
    pakt s(ync-)u(ninstall) (file | +cat)...      uninstall several packages from categories
                                                    or arbitary files
    pakt l(ist)             ls-arg...             list all user-defined categories
    pakt c(at)              (file | +cat)...      list all packages in the given categories
    pakt f(ind)             pkg...                list categories the given packages are in
    pakt e(dit)             (file | +cat)...      edit category or arbitary files manually
    pakt p(urge)            +cat...               remove entire category files
    pakt n(ative)           pm-arg...             perform a regular package manager operation
    pakt h(elp)                                   print this message

Configuration:
    $PAKT_CONF_PATH/pakt.conf

About:
    v1.1.2  GPL-3.0  https://github.com/mminl-de/pakt
    Sergey Lavrent <https://github.com/hiimsergey>
    MrMineDe <https://github.com/mrminede>"
}

# Constructs a multiline string table of involved packages and their corresponding
# categories, given an argument list, and stores it in $pairs.
# Parses package manager flags and saves them in $cmd_args.
# $pairs has this format:
#
# pkg1 cat1 cat2 ... catN : comment...
# pkg2 cat1 ... : ...
# pkg3 ... : ...
# ...
construct_pairs() {
	cmd_args=""
	pairs=""
	pkgs=""
	cats=""
	comm=""
	expecting_comm=0

	for arg; do
		[ $expecting_comm -eq 1 ] && {
			comm="$arg"
			expecting_comm=0
			continue
		}
		case "$arg" in
			$CAT_SYNTAX$CAT_SYNTAX)
				cats=$(ls "$PAKT_CAT_PATH" | tr "\n" " ")
				;;
			$CAT_SYNTAX*)
				cats="$cats ${arg#$CAT_SYNTAX}"
				;;
			:)
				expecting_comm=1
				;;
			-*)
				cmd_args="$cmd_args $arg"
				;;
			*)
				[ -n "$cats" ] && update_pairs
				pkgs="$pkgs\n$arg"
				cmd_args="$cmd_args $arg"
				;;
		esac
	done
	update_pairs
}

# Adds new lines of the format "<pkg> $cats" to $pairs, where <pkg> is every
# package listed in $pkgs.
# Sets both $pkgs and $cats to empty strings afterwards.
update_pairs() {
	IFS= read -r _ # skip empty first line
	while IFS= read -r pkg; do
		pairs="$pairs\n$pkg $cats $DEFAULT_CATS"
	done <<EOF
$(printf "$pkgs\n")
EOF
	echo -e "TODO once pairs '$pairs'"
	[ -n "$comm" ] && [ -n "$pairs" ] && pairs="$pairs:$comm" || \
		fail "You can only place comments right after package names!
See 'pakt help' for correct usage!" # TODO CONSIDER expanding the help page or use a man page
	pkgs=""
	cats=""
	comm=""
}

# Reads the table expressed in $pairs and writes the names of the packages into
# the files of their assigned categories, only if they weren't listed there before.
write_from_pairs() {
	IFS= read -r _ # skip empty first line
	printf "$pairs\n" | while IFS= read -r line; do
		uncommented=$(printf "%s\n" "$line" | sed "s/:.*//")
		comment=$(printf "%s\n" "$line" | sed -n "s/.*://p")

		set -- $uncommented
		pkg="$1"
		shift
		for cat; do
			file="$PAKT_CAT_PATH/$cat"
			grep -F "$pkg" "$file" >/dev/null 2>&1 || {
				file_line="$pkg"
				[ -n "$comment" ] && file_line="$file_line # $comment"
				echo "$file_line" >> "$file"
			}
		done
	done
}

# Reads the table expressed in $pairs and removes the names of the packages from
# the files of their assigned categories.
delete_from_pairs() {
	IFS= read -r _ # skip empty first line
	printf "$pairs\n" | while IFS= read -r line; do
		set -- $line
		pkg="$1"
		shift
		for cat; do
			file="$PAKT_CAT_PATH/$cat"
			filtered=""
			while IFS= read -r line; do
				# strip comments
				uncommented=$(printf "%s\n" "$line" | sed "s/[[:space:]]*#.*//")
				[ -z "$uncommented" ] && continue

				case " $uncommented " in
					*" $pkg "*) ;;
					*) filtered="$filtered$line\n"; ;;
				esac
			done < "$file"
			printf "$filtered" > "$file"
		done
	done
}

# Takes a list of arguments, replaces those starting with the
# Pakt category syntax marker with their respective category files and stores
# the resulting list in $files.
construct_file_list() {
	files=""
	for arg; do
		case "$arg" in
			$CAT_SYNTAX$CAT_SYNTAX)
				files=$(find "$PAKT_CAT_PATH")
				;;
			$CAT_SYNTAX*)
				files="$files $PAKT_CAT_PATH/${arg#$CAT_SYNTAX}"
				;;
			*)
				files="$files $arg"
				;;
		esac
	done
}

case "$1" in
	install|i)
		shift
		# TODO DEBUG ts doesnt work for if the sole args are flags
		[ $# -eq 0 ] && \
			fail "Missing package names!\nSee 'pakt help' for correct usage!"
		construct_pairs "$@"
		cmd="$PACKAGE_MANAGER $INSTALL_ARG $cmd_args"
		$cmd && write_from_pairs
		;;
	uninstall|u)
		shift
		# TODO ALL DEBUG ts doesnt work for if the sole args are flags
		[ $# -eq 0 ] && \
			fail "Missing package names!\nSee 'pakt help' for correct usage!"
		construct_pairs "$@"
		cmd="$PACKAGE_MANAGER $UNINSTALL_ARG $cmd_args"
		$cmd && delete_from_pairs

		[ $REMOVE_EMPTY_CATS -eq 1 ] && find "$PAKT_CAT_PATH" -empty -delete || true
		;;
	dry-install|di)
		shift
		[ $# -eq 0 ] && \
			fail "Missing package names!\nSee 'pakt help' for correct usage!"
		construct_pairs "$@"
		write_from_pairs
		;;
	dry-uninstall|du)
		shift
		[ $# -eq 0 ] && \
			fail "Missing package names!\nSee 'pakt help' for correct usage!"
		construct_pairs "$@"
		delete_from_pairs

		[ $REMOVE_EMPTY_CATS -eq 1 ] && find "$PAKT_CAT_PATH" -empty -delete || true
		;;
	# TODO HANDLE inline comments
	sync-install|si)
		shift
		[ $# -eq 0 ] && \
			fail "Missing category names/file paths!\nSee 'pakt help' for correct usage!"
		construct_file_list "$@"
		$PACKAGE_MANAGER $INSTALL_ARG \
			$(sed -e "s/[[:space:]]*#.*//; /^[[:space:]]*$/d" $files | tr "\n" " ")
		;;
	# TODO HANDLE inline comments
	sync-uninstall|su)
		shift
		[ $# -eq 0 ] && \
			fail "Missing category names/file paths!\nSee 'pakt help' for correct usage!"
		construct_file_list "$@"
		$PACKAGE_MANAGER $UNINSTALL_ARG \
			$(sed -e "s/[[:space:]]*#.*//; /^[[:space:]]*$/d" $files | tr "\n" " ")
		;;
	list|l)
		shift
		ls "$@" "$PAKT_CAT_PATH"
		;;
	cat|c)
		shift
		[ $# -eq 0 ] && \
			fail "Missing category names/file paths!\nSee 'pakt help' for correct usage!"
		construct_file_list "$@"

		# 1. strip away comments, 2. strip away empty lines
		sed -e "s/[[:space:]]*#.*//; /^[[:space:]]*$/d" $files
		;;
	find|f)
		shift
		[ $# -eq 0 ] && \
			fail "Missing package names!\nSee 'pakt help' for correct usage!"
		result=""
		for arg; do
			for file in "$PAKT_CAT_PATH"/*; do
				# 1. strip away comments
				if sed "s/[[:space:]]*#.*//" "$file" | \
					# 2. match against whole words
					grep -E "(^|[[:space:]])$arg($|[[:space:]])" >/dev/null 2>&1; then
					result="$result$(basename "$file")\n"
				fi
			done
		done
		[ -z "$result" ] && exit 1 || printf "$result"
		;;
	edit|e)
		shift
		construct_file_list "$@"
		$PAKT_EDITOR $files
		;;
	purge|p)
		shift
		[ $# -eq 0 ] && \
			fail "Missing category names!\nSee 'pakt help' for correct usage!"
		cats=""
		for arg; do
			case "$arg" in
				$CAT_SYNTAX$CAT_SYNTAX)
					for cat in $(ls "$PAKT_CAT_PATH"); do
						cats="$cats $CAT_SYNTAX$cat"
					done
					;;
				$CAT_SYNTAX*)
					cats="$cats $arg"
					;;
				*)
					fail "'$arg' is not a category!\nSee 'pakt help' for correct usage!"
					;;
			esac
		done
		construct_file_list $cats

		printf "$cats\nAre you sure you want to delete these categories? [y/N] "
		read response
		case "$response" in
			[y/Y]|[y/Y][e/E][s/S]) rm -v $files; ;;
			*) exit 1; ;;
		esac
		;;
	native|n)
		shift
		$PACKAGE_MANAGER "$@"
		;;
	help|h)
		help
		exit
		;;
	*)
		fail "Invalid subcommand '$1'!\nSee 'pakt help' for available options!"
		;;
esac
