#!/bin/sh
# pakt – a package manager wrapper with support for categorizing
# v1.0.0  GPL-3.0
# https://github.com/mminl-de/pakt

set -eu

# Setting default options for config variables
: "${PAKT_CONF_PATH:=${XDG_CONFIG_HOME:-$HOME/.config}}"
: "${PAKT_EDITOR:=${EDITOR:-nano}}"
: "${CAT_SYNTAX:="+"}"
: "${NO_ARG_ACTION:="pakt help"}"
: "${PAKT_CAT_PATH:=${XDG_DATA_HOME:-$HOME/.local/share}/pakt}"
: "${DEFAULT_CATS:=""}"
mkdir -p "$PAKT_CAT_PATH"

. "$PAKT_CONF_PATH/pakt.conf"

if [ $# -eq 0 ]; then
	$NO_ARG_ACTION
	exit
fi

# Just prints a help message.
help() {
	echo "pakt – a package manager wrapper with support for categorizing

Usage:
    pakt                                      perform a user-defined arbitrary action
    pakt install        (pkg [+cat ...])...   install packages
    pakt uninstall      (pkg [+cat ...])...   uninstall packages
    pakt dry-install    (pkg [+cat ...])...   write packages into categories without
                                                installing them
    pakt dry-uninstall  (pkg [+cat ...])...   remove packages from categories without
                                                uninstalling them
    pakt sync-install   (file | +cat)...      install several packages from categories
                                                or arbitrary files
    pakt sync-uninstall (file | +cat)...      uninstall several packages from categories
                                                or arbitary files
    pakt list           list-arg...           list all user-defined categories
    pakt cat            +cat...               list all packages in the given categories
    pakt find           pkg...                list categories the given packages are in
    pakt native         arg...                perform a regular package manager operation
    pakt edit           (file | +cat)...      manually edit category or arbitary files
    pakt help                                 print this message

Configuration:
    $PAKT_CONF_PATH/pakt.conf"
}

# Prints a given message in red.
error() {
	printf "\x1b[31m$1\x1b[39m\n"
}

# Constructs a multiline string table of involved packages and their corresponding
# categories, given an argument list, and stores it in $pairs.
# Parses package manager flags and saves them in $cmd_args.
# $pairs has this format:
#
# pkg1 cat1 cat2 ... catN
# pkg2 cat1 ...
# pkg3 ...
# ...
construct_pairs() {
	cmd_args=""
	pairs=""
	pkgs=""
	cats=""

	for arg; do
		case "$arg" in
			$CAT_SYNTAX$CAT_SYNTAX)
				cats=$(ls "$PAKT_CAT_PATH")
				;;
			$CAT_SYNTAX*)
				cats="$cats ${arg#?}"
				;;
			-*)
				cmd_args="$cmd_args $arg"
				;;
			*)
				[ -n "$cats" ] && update_pairs
				pkgs="$pkgs $arg"
				cmd_args="$cmd_args $arg"
				;;
		esac
	done
	update_pairs
}

# Adds new lines of the format "<pkg> $cats" to $pairs, where <pkg> is every
# package listed in $pkgs.
# Sets both $pkgs and $cats to empty strings afterwards.
update_pairs() {
	for pkg in "$pkgs"; do
		pairs="$pairs $pkg $cats $DEFAULT_CATS\n"
	done
	pkgs=""
	cats=""
}

# Reads the table expressed in $pairs and writes the names of the packages into
# the files of their assigned categories, only if they weren't listed there before.
write_from_pairs() {
	printf "$pairs\n" | while IFS= read -r line; do
		[ -z "$line" ] && continue
		set -- $line
		pkg="$1"
		shift
		for cat; do
			file="$PAKT_CAT_PATH/$cat"
			grep -F "$pkg" "$file" >/dev/null 2>&1 || echo "$pkg" >> "$file"
		done
	done
}

# Reads the table expressed in $pairs and removes the names of the packages from
# the files of their assigned categories.
delete_from_pairs() {
	printf "$pairs\n" | while IFS= read -r line; do
		[ -z "$line" ] && continue
		set -- $line
		pkg="$1"
		shift
		for cat; do
			file="$PAKT_CAT_PATH/$cat"
			sed -i "/^$pkg$/d" "$file"
		done
	done
}

# Takes a list of arguments, replaces those starting with the
# Pakt category syntax marker with their respective category files and stores
# the resulting list in $files.
construct_file_list() {
	files=""
	for arg; do
		case "$arg" in
			$CAT_SYNTAX$CAT_SYNTAX)
				files=$(find "$PAKT_CAT_PATH")
				;;
			$CAT_SYNTAX*)
				files="$files $PAKT_CAT_PATH/${arg#?}"
				;;
			*)
				files="$files $arg"
				;;
		esac
	done
}

case "$1" in
	install|i)
		shift
		if [ $# -eq 0 ]; then
			error "Missing package names!\nSee 'pakt help' for correct usage!"
			exit 1
		fi
		construct_pairs "$@"
		cmd="$PACKAGE_MANAGER $INSTALL_ARG $cmd_args"
		$cmd && write_from_pairs
		;;
	uninstall|u)
		shift
		if [ $# -eq 0 ]; then
			error "Missing package names!\nSee 'pakt help' for correct usage!"
			exit 1
		fi
		construct_pairs "$@"
		cmd="$PACKAGE_MANAGER $UNINSTALL_ARG $cmd_args"
		$cmd && delete_from_pairs

		[ $REMOVE_EMPTY_CATS -eq 1 ] && find "$PAKT_CAT_PATH" -empty -delete || true
		;;
	dry-install|di)
		shift
		if [ $# -eq 0 ]; then
			error "Missing package names!\nSee 'pakt help' for correct usage!"
			exit 1
		fi
		construct_pairs "$@"
		write_from_pairs
		;;
	dry-uninstall|du)
		shift
		if [ $# -eq 0 ]; then
			error "Missing package names!\nSee 'pakt help' for correct usage!"
			exit 1
		fi
		construct_pairs "$@"
		delete_from_pairs

		[ $REMOVE_EMPTY_CATS -eq 1 ] && find "$PAKT_CAT_PATH" -empty -delete || true
		;;
	sync-install|si)
		shift
		if [ $# -eq 0 ]; then
			error "Missing category names/file paths!\nSee 'pakt help' for correct usage!"
			exit 1
		fi
		construct_file_list "$@"
		$PACKAGE_MANAGER $INSTALL_ARG $(grep -rvh "#" $files)
		;;
	sync-uninstall|su)
		shift
		if [ $# -eq 0 ]; then
			error "Missing category names/file paths!\nSee 'pakt help' for correct usage!"
			exit 1
		fi
		construct_file_list "$@"
		echo "$PACKAGE_MANAGER $UNINSTALL_ARG $(grep -rvh "#" $files)"
		;;
	list|l)
		shift
		ls "$@" "$PAKT_CAT_PATH"
		;;
	cat|c)
		shift
		if [ $# -eq 0 ]; then
			error "Missing category names/file paths!\nSee 'pakt help' for correct usage!"
			exit 1
		fi
		construct_file_list "$@"
		echo $(grep -rvh "#" $files)
		;;
	find|f)
		shift
		[ $# -eq 0 ] && {
			error "Missing package names!\nSee 'pakt help' for correct usage!"
			exit 1
		}
		result=""
		for arg; do
			for file in $(grep -rl "$arg" "$PAKT_CAT_PATH"); do
				result="$result$(basename "$file")\n"
			done
		done
		[ -z "$result" ] && exit 1
		printf "$result"
		;;
	native|n)
		shift
		$PACKAGE_MANAGER "$@"
		;;
	edit|e)
		shift
		construct_file_list "$@"
		$PAKT_EDITOR $files
		;;
	help|h)
		help
		exit
		;;
	*)
		error "Invalid subcommand '$1'!
See 'pakt help' for available options!\x1b[39m"
		exit 1
		;;
esac
